sudo: required
services: 
  - docker
before_install: 
  - docker build -t kiranbhalerao123/docker-react -f Dockerfile.dev .

script: 
  - docker run kiranbhalerao123/docker-react npm run test -- --coverage

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: "kiranbhalerao-docker-react"
  on: master